<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5576d437eda35',
	'title' => 'Page About',
	'fields' => array (
		array (
			'key' => 'field_5576d44b2b611',
			'label' => 'Portrait',
			'name' => 'about_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-about.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_557df463c185c',
	'title' => 'Page Home',
	'fields' => array (
		array (
			'key' => 'field_557df46907254',
			'label' => 'Full Screen Images',
			'name' => 'full_screen_img',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '75',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
));

acf_add_local_field_group(array (
	'key' => 'group_54e27bf90d74f',
	'title' => 'Project',
	'fields' => array (
		array (
			'key' => 'field_55772460195dd',
			'label' => 'Images',
			'name' => 'rep_img',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Image',
			'sub_fields' => array (
				array (
					'key' => 'field_55772469195de',
					'label' => 'Image',
					'name' => 'wall_img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'large',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_557724b75e415',
					'label' => 'Wall Caption',
					'name' => 'wall_capt',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'br',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5577258d8a264',
					'label' => 'Image Padding',
					'name' => 'rep_thumb_pad',
					'type' => 'checkbox',
					'instructions' => 'Space around Image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'pdt-3' => 'Top 3em',
						'pdt-4' => 'Top 4em',
						'pdt-5' => 'Top 5em',
						'pdt-6' => 'Top 6em',
						'pdr-3' => 'Right 3em',
						'pdr-4' => 'Right 4em',
						'pdr-5' => 'Right 5em',
						'pdr-6' => 'Right 6em',
						'pdb-3' => 'Bottom 3em',
						'pdb-4' => 'Bottom 4em',
						'pdb-5' => 'Bottom 5em',
						'pdb-6' => 'Bottom 6em',
						'pdl-3' => 'Left 3em',
						'pdl-4' => 'Left 4em',
						'pdl-5' => 'Left 5em',
						'pdl-6' => 'Left 6em',
					),
					'default_value' => array (
						'' => '',
					),
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_557725a68a265',
					'label' => 'Image Size',
					'name' => 'rep_thumb_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'ThWidth' => 'Thumbnail size - Width 100',
						'XSWidth' => 'X-Small size - Width 150',
						'SWidth' => 'Small size - Width 200',
						'SMWidth' => 'Small-Medium size - Width 250',
						'MWidth' => 'Medium size - Width 350',
						'LWidth' => 'Large size - Width 450',
						'XLWidth' => 'X-Large size - Width 520',
						'XXLWidth' => 'XX-Large size - Width 600',
						'XXXLWidth' => 'XXX-Large size - Width 900',
					),
					'default_value' => array (
						'' => '',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'author',
		6 => 'send-trackbacks',
	),
));

acf_add_local_field_group(array (
	'key' => 'group_55772604c0dd5',
	'title' => 'Project Side',
	'fields' => array (
		array (
			'key' => 'field_53c54f44eeee0',
			'label' => 'Thumbnail Size',
			'name' => 'thumbnail_size',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'ThWidth' => 'Thumbnail size - Width 100',
				'XSWidth' => 'X-Small size - Width 150',
				'SWidth' => 'Small size - Width 200',
				'SMWidth' => 'Small-Medium size - Width 250',
				'MWidth' => 'Medium size - Width 350',
				'LWidth' => 'Large size - Width 450',
				'XLWidth' => 'X-Large size - Width 520',
				'XXLWidth' => 'XX-Large size - Width 600',
				'XXXLWidth' => 'XXX-Large size - Width 900',
			),
			'default_value' => array (
				'' => '',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_557593c164403',
			'label' => 'Thumbnails Padding',
			'name' => 'thumb_pad',
			'type' => 'checkbox',
			'instructions' => 'Space around featured Image ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'pdt-3' => 'Top Padding 3em',
				'pdt-4' => 'Top Padding 4em',
				'pdt-5' => 'Top Padding 5em',
				'pdt-6' => 'Top Padding 6em',
				'pdr-3' => 'Right Padding 3em',
				'pdr-4' => 'Right Padding 4em',
				'pdr-5' => 'Right Padding 5em',
				'pdr-6' => 'Right Padding 6em',
				'pdb-3' => 'Bottom Padding 3em',
				'pdb-4' => 'Bottom Padding 4em',
				'pdb-5' => 'Bottom Padding 5em',
				'pdb-6' => 'Bottom Padding 6em',
				'pdl-3' => 'Left Padding 3em',
				'pdl-4' => 'Left Padding 4em',
				'pdl-5' => 'Left Padding 5em',
				'pdl-6' => 'Left Padding 6em',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;